### ISSUE TITLE
Implement control for the repository format in format.yaml

### ISSUE THREAD

**Issue by lukasburda** [xstefank/tyr#26]

**Comment by xstefank** [comment]
Are you thinking about traditional check implementing the `Check` interface? In that case where the error would be displayed?

**Comment by lukasburda** [comment]
I think it would be better to implement this feature to function where format.yaml loads and if there is bad format throw some exception.

**Comment by xstefank** [comment]
@lukasburda so the current implementation loads the application when invalid format.yaml is passed in?

**Comment by lukasburda** [comment]
@xstefank yes it does

**Comment by lukasburda** [comment]
No, but if you type to format.yaml bad repository value like "user/repo/somethingelse" or "userrepo" it loads. I think it would be better to warn user that it has bad format.

**Comment by xstefank** [comment]
I understand now your concern, please go ahead, looking forward to the PR!
